baseURL = "https://hamymusic.com/"
defaultContentLanguage = "fi"

title = "HÄMY"

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.fi]
    title = "HÄMY"
    languageCode = "fi"
    contentDir = "content/fi"
    weight = 1

    [languages.fi.params]
    description = "Uniikkia ja valtavirrasta poikkeavaa musiikkia"

  [languages.en]
    title = "HÄMY"
    languageCode = "en"
    contentDir = "content/en"
    weight = 2

    [languages.en.params]
    description = "Unique music beyond the mainstream"



[params]
media =[
    { url = "/kuvat/2023 Kuva Jussi Määttä.jpg", alt = "(C) Jussi Määttä" },
    { url = "/kuvat/2023 Hämy 1 Jussi Määttä.jpg", alt = "(C) Jussi Määttä" },
    { url = "/kuvat/2022 Samuel Vielma.jpg", alt = "(C) Samuel Vielma" },
    { url = "/kuvat/2020 Filip Smeds.jpg", alt = "(C) Filip Smed" }
]


