baseURL = "http://localhost:1313"

title = "HÄMY"

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
[languages.fi]
  title = "HÄMY"
  languageCode = "fi"
  contentDir = "content/fi"

[languages.en]
  title = "HÄMY"
  languageCode = "en"
  contentDir = "content/en"


