backend:
  name: git-gateway
  branch: main
  identity_url: https://hamymusic.netlify.app/.netlify/identity

media_folder: "static/kuvat"
public_folder: "/kuvat"

collections:
  - name: 'fi-about'
    preview_path: '/fi/about'
    label: 'about (FI)'
    files:
      - file: 'content/fi/about.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', id: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', id: 'body', widget: 'markdown' }
          - { label: 'Intro Video URL', name: 'introvideo_src', id: 'introvideo_src', widget: 'string' }


  - name: 'fi-gigs'
    preview_path: '/fi/gigs'
    label: 'Performances (FI)'
    files:
      - file: 'content/fi/gigs.md'
        label: 'Gigs'
        name: 'gigs'
        fields:
          - { label: 'Gig Title', name: 'title', widget: 'string' }
          - { label: 'Gig Image', name: 'gig_image', id: 'gig_image', widget: 'image' }
          - { label: 'Gig Description', name: 'gig_description', id: 'gig_description', widget: 'markdown' }

  - name: 'fi-diskografia'
    preview_path: '/fi/diskografia'
    label: 'Diskografia (FI)'
    files:
      - file: 'content/fi/diskografia.md'
        label: 'Diskografia'
        name: 'diskografia'
        fields:
          - { label: 'Albums', name: 'albums', id: 'albums', widget: 'list', fields: [
              { label: 'Image', name: 'image', widget: 'image' },
              { label: 'Title', name: 'title', widget: 'string' },
              { label: 'Type', name: 'type', widget: 'select', options: ['single', 'albumi'] },
              { label: 'Year', name: 'year', widget: 'string' }
            ]
          }

  - name: 'fi-musicvideos'
    preview_path: '/fi/musicvideos'
    label: 'Music Videos (FI)'
    files:
      - file: 'content/fi/musicvideos.md'
        label: 'Music Videos'
        name: 'musicvideos'
        fields:
          - { label: 'videos', name: 'videos', id: 'videos', widget: 'list', fields: [
              { label: 'Video ID', name: 'video_id', widget: 'string' },
              { label: 'Upload Date', name: 'upload_date', widget: 'datetime' }
            ]
          }

  - name: 'fi-media'
    preview_path: '/fi/media'
    label: 'Media (FI)'
    files:
      - file: 'content/fi/media.md'
        label: 'Media'
        name: 'media'
        fields:
          - { label: 'Media', name: 'media', id: 'media', widget: 'list', fields: [
              { label: 'URL', name: 'url', widget: 'string' },
              { label: 'Alt Text', name: 'alt', widget: 'string' }
            ]
          }

  - name: 'fi-contact'
    preview_path: '/fi/contact'
    label: 'Contact (FI)'
    files:
      - file: 'content/fi/contact.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - { label: 'Title', name: 'title', id: 'title', widget: 'string' }
          - { label: 'Contact Information', name: 'contact_info', id: 'contact_info', widget: 'markdown' }


  - name: 'en-about'
    preview_path: '/en/about'  
    label: 'about (EN)'
    files:
      - file: 'content/en/about.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', id: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', id: 'body', widget: 'markdown' }
          - { label: 'Intro Video URL', name: 'introvideo_src', id: 'introvideo_src', widget: 'string' }

  - name: 'en-gigs'
    preview_path: '/en/gigs'
    label: 'Performances (EN)'
    files:
      - file: 'content/en/gigs.md'
        label: 'Gigs'
        name: 'gigs'
        fields:
          - { label: 'Gig Title', name: 'title', widget: 'string' }
          - { label: 'Gig Image', name: 'gig_image', id: 'gig_image', widget: 'image' }
          - { label: 'Gig Description', name: 'gig_description', id: 'gig_description', widget: 'markdown' }

  - name: 'en-diskografia'
    preview_path: '/en/diskografia'
    label: 'Discography (EN)'
    files:
      - file: 'content/en/diskografia.md'
        label: 'Discography'
        name: 'diskografia'
        fields:
          - { label: 'Albums', name: 'albums', id: 'albums', widget: 'list', fields: [
              { label: 'Image', name: 'image', widget: 'image' },
              { label: 'Title', name: 'title', widget: 'string' },
              { label: 'Type', name: 'type', widget: 'select', options: ['single', 'album'] },
              { label: 'Year', name: 'year', widget: 'string' }
            ]
          }


  - name: 'en-musicvideos'
    preview_path: '/en/musicvideos'  
    label: 'Music Videos (EN)'
    files:
      - file: 'content/en/musicvideos.md'
        label: 'Music Videos'
        name: 'musicvideos'
        fields:
          - { label: 'videos', name: 'videos', id: 'videos', widget: 'list', fields: [
              { label: 'Video ID', name: 'video_id', widget: 'string' },
              { label: 'Upload Date', name: 'upload_date', widget: 'datetime' }
            ]
          }

  - name: 'en-media'
    preview_path: '/en/media'
    label: 'Media (EN)'
    files:
      - file: 'content/en/media.md'
        label: 'Media'
        name: 'media'
        fields:
          - { label: 'Media', name: 'media', id: 'media', widget: 'list', fields: [
              { label: 'URL', name: 'url', widget: 'string' },
              { label: 'Alt Text', name: 'alt', widget: 'string' }
            ]
          }
         

  - name: 'en-contact'
    preview_path: '/en/contact'
    label: 'Contact (EN)'
    files:
      - file: 'content/en/contact.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - { label: 'Title', name: 'title', id: 'title', widget: 'string' }
          - { label: 'Contact Information', name: 'contact_info', id: 'contact_info', widget: 'markdown' }

